@include('sections.header')
@include('sections.hero')
@include('sections.restaurants')
@include('sections.signature-dishes')
@include('sections.icon-definitions')
@include('sections.week-chef')
@include('sections.about-us')
